spring:
  application:
    name: dine-in-order-api

  datasource:
    url: jdbc:mysql://localhost:3306/dine_in_db?createIfNotExists=true
    username: root
    password: root
  jpa:
    hibernate:
        ddl-auto: update
        show-sql: true
