spring:
  application:
    name: dine-in-order-api

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: update

app:
  base-url: /api/v1
  cloudinary:
    cloud-name: ${CLOUD_NAME}
    api-key: ${API-KEY}
    api-secret: ${API-SECRET}